apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-sse-service
spec:
  selector:
    matchLabels:
      app: sb-sse-service
  replicas: 1
  template:
    metadata:
      labels:
        app: sb-sse-service
        env: development
    spec:
      containers:
        - name: sb-sse-service
          image: eu.gcr.io/ssil1-258911/sb-sse-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sb-sse-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: sb-sse-service